(function(){
'use strict';
const W=window.SlogiWorkflow,P=window.SlogiPro,$=id=>document.getElementById(id),esc=v=>W.escape(v);
let id=W.projectId(),project=null,dirty=false,attachments={};
const fields=[
  ['clusterName','Кластер','text'],['managerName','Ответственный','text'],['legalEntity','Юридическое лицо','text'],
  ['landlord','Арендодатель','text'],['landlordContact','Контактное лицо','text'],['contractNumber','Номер договора','text'],
  ['area','Площадь, м²','number'],['floor','Этаж','text'],['floorEntrance','Этаж / вход','text'],
  ['openingDate','Плановая дата открытия','date'],['actualOpeningDate','Фактическая дата открытия','date'],['ceilingHeight','Высота потолков, м','select'],
  ['power','Электрическая мощность, кВт','number'],['accessHours','Часы доступа','text'],['noiseHours','Режим шумных работ','text'],
  ['ventilation','Вентиляция','text'],['phone','Телефон','text'],['email','Email','email'],['site','Сайт','text'],
  ['specialConditions','Особые условия объекта','textarea','full']
];
const STAGES=[
  {id:1,name:'Первичная оценка объекта',duration:'1 рабочий день',result:'Принято решение о проведении замера или отказе от объекта',criteria:['Технические условия проверены','Объект соответствует критериям выбранного кластера','Предварительная смета подготовлена и одобрена','Решение о проведении замера зафиксировано'],docs:[['technicalConditions','Технические условия'],['preliminaryEstimate','Предварительная смета']]},
  {id:2,name:'Замеры и расчёт концепции',duration:'до 7 дней',result:'Готовы планировка, расчётная спецификация, точная смета, сроки и проект КП',criteria:['Замер помещения выполнен','Планировка подготовлена','Расчётная спецификация проверена и подтверждена','Рассчитаны стоимость и срок ремонта','Подготовлен проект коммерческого предложения'],docs:[['plan','Обмерный план / планировка'],['spec','Расчётная спецификация'],['estimate','Рабочая смета'],['proposal','Коммерческое предложение']]},
  {id:3,name:'Согласование условий аренды',duration:'до 7 дней',result:'Условия аренды согласованы, договор готов к подписанию',criteria:['Документы о собственности проверены','Проект договора аренды получен и проверен','Замечания и коммерческие условия согласованы','Протокол разногласий утверждён','Договор аренды подписан'],docs:[['propertyDocuments','Документы о собственности'],['leaseAgreement','Договор аренды'],['disagreementProtocol','Протокол разногласий']]},
  {id:4,name:'Подготовка к ремонту',duration:'до передачи помещения',result:'Закупки, подрядчики, сроки и платежи готовы к запуску',criteria:['Список заказных позиций утверждён','Закупочная спецификация утверждена','Поставщики и подрядчики определены','Заказные позиции запущены в производство','График работ утверждён','График платежей утверждён'],docs:[['orderedPositions','Список заказных позиций'],['procurementSpec','Закупочная спецификация'],['contractorAgreements','Договоры с подрядчиками'],['gantt','Диаграмма Ганта'],['payments','График платежей']]},
  {id:5,name:'Ремонт и подготовка к открытию',duration:'до 30 дней',result:'Работы завершены, объект готов к финальной приёмке',criteria:['Подрядчики вышли на объект','Закупки и поставки контролируются','Этапы графика закрываются без критических отклонений','Счета, акты и подтверждения загружены','Мебель и оборудование поставлены'],docs:[['eArchive','Электронный архив закупок'],['purchaseReports','Отчётность о закупках']]},
  {id:6,name:'Открытие и закрытие проекта',duration:'по готовности объекта',result:'Объект передан в эксплуатацию, проект закрыт',criteria:['Финальная приёмка проведена','Замечания устранены','Итоговая стоимость зафиксирована','Все платежи закрыты','Архив документов собран','Объект передан операционной команде','Фактическая дата открытия указана'],docs:[['completionAct','Акт приёмки'],['finalEstimate','Финальная смета'],['paymentRegister','Реестр оплат'],['finalReport','Итоговый отчёт']]}
];
const DOCS=[
  {key:'technicalConditions',stage:1,title:'Технические условия',desc:'Проверка соответствия помещения базовым требованиям.',kind:'upload'},
  {key:'preliminaryEstimate',stage:1,title:'Предварительная смета',desc:'Первичная бюджетная оценка до детального расчёта.',kind:'upload'},
  {key:'plan',stage:2,title:'Обмерный план / планировка',desc:'План помещения после замера.',kind:'upload'},
  {key:'spec',stage:2,title:'Расчётная спецификация',desc:'Редактируемый источник данных для формирования точной сметы.',kind:'editor',href:'source-specification.html'},
  {key:'estimate',stage:2,title:'Рабочая смета',desc:'Расчёт по подтверждённой спецификации.',kind:'editor',href:'specification.html'},
  {key:'proposal',stage:2,title:'Коммерческое предложение',desc:'КП на корпоративном бланке с версиями.',kind:'editor',href:'proposal.html'},
  {key:'propertyDocuments',stage:3,title:'Документы о собственности',desc:'Пакет документов, подтверждающих права на помещение.',kind:'upload'},
  {key:'leaseAgreement',stage:3,title:'Договор аренды',desc:'Актуальная согласованная редакция договора.',kind:'upload'},
  {key:'disagreementProtocol',stage:3,title:'Протокол разногласий',desc:'Замечания и согласованная редакция условий.',kind:'upload'},
  {key:'orderedPositions',stage:4,title:'Список заказных позиций',desc:'Позиции, переданные в производство или закупку.',kind:'upload'},
  {key:'procurementSpec',stage:4,title:'Закупочная спецификация',desc:'Утверждённый состав закупок для запуска ремонта и поставок.',kind:'upload'},
  {key:'contractorAgreements',stage:4,title:'Договоры с подрядчиками',desc:'Комплект договоров и приложений к запуску работ.',kind:'upload'},
  {key:'eArchive',stage:5,title:'Электронный архив закупок',desc:'Счета, чеки, акты и подтверждения закупок.',kind:'upload'},
  {key:'purchaseReports',stage:5,title:'Отчётность о закупках',desc:'Сводная отчётность по закупкам и поставкам.',kind:'upload'},
  {key:'completionAct',stage:6,title:'Акт приёмки',desc:'Документ о завершении и приёмке работ.',kind:'upload'},
  {key:'finalEstimate',stage:6,title:'Финальная смета',desc:'Фактическая итоговая стоимость объекта.',kind:'upload'},
  {key:'paymentRegister',stage:6,title:'Реестр оплат',desc:'Итоговый реестр всех платежей по объекту.',kind:'upload'},
  {key:'finalReport',stage:6,title:'Итоговый отчёт',desc:'Сводный отчёт и передача проекта в эксплуатацию.',kind:'upload'}
];
const EXTRA_DOWNLOADS=['spec-edited','proposal-pdf'];
function uid(){return crypto.randomUUID?crypto.randomUUID():'loc-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)}
function money(v){return Math.round(Number(v)||0).toLocaleString('ru-RU')+' ₽'}
function date(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('ru-RU')}
function msg(mode,text){const e=$('passport-status');e.className='passport-status'+(mode?' '+mode:'');e.textContent=text||''}
function stageById(n){return STAGES.find(x=>x.id===Number(n))||STAGES[0]}
function currentStage(){return Math.min(6,Math.max(1,Number(project.stage||project.phase)||1))}
function createIfNeeded(){
  if(project)return;
  id=id||uid();
  project={id,address:'',status:'Новый',stage:1,phase:1,stageChecks:{},clusterName:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),gantt:[],paymentSchedule:[]};
  const all=W.readLocations();all.unshift(project);W.writeLocations(all);localStorage.setItem('slogi_active_project_v1',id);history.replaceState({},'',`passport.html?location=${encodeURIComponent(id)}`);
}
function statuses(){const list=P?P.read().settings.statuses:['Новый','В работе','Ожидает информации','На согласовании','Требует решения','Приостановлен','Просрочен','Завершён','Отказ'];$('status').innerHTML=list.map(x=>`<option>${esc(x)}</option>`).join('');$('status').value=project.status||project.projectStatus||'Новый'}
function stagesSelect(){$('current-stage').innerHTML=STAGES.map(s=>`<option value="${s.id}">${s.id}. ${esc(s.name)}</option>`).join('');$('current-stage').value=String(currentStage())}
function form(){const root=$('passport-form');root.innerHTML=fields.map(([k,l,t,cl])=>`<div class="passport-field ${cl||''}"><label>${l}</label>${t==='textarea'?`<textarea data-field="${k}">${esc(project[k]||'')}</textarea>`:t==='select'?`<select data-field="${k}"><option value="3">3 м</option><option value="6">6 м</option></select>`:`<input data-field="${k}" type="${t}" value="${esc(project[k]??'')}">`}</div>`).join('');root.querySelectorAll('[data-field]').forEach(e=>{if(e.dataset.field==='ceilingHeight')e.value=String(project.ceilingHeight||3);e.addEventListener('input',()=>dirty=true);e.addEventListener('change',()=>dirty=true)})}
function docReady(key){
  if(key==='gantt')return Array.isArray(project.gantt)&&project.gantt.length>0;
  if(key==='payments')return Array.isArray(project.paymentSchedule)&&project.paymentSchedule.length>0;
  if(key==='spec')return Boolean(project.sourceSpecificationModel||project.specName||attachments.spec||attachments['spec-edited']);
  if(key==='estimate')return Boolean(project.estimateModel||project.estimateName||attachments.estimate);
  if(key==='proposal')return Boolean(project.proposalParagraphs||project.proposalName||attachments.proposal);
  if(key==='plan')return Boolean(project.planName||attachments.plan);
  return Boolean(project[key+'Name']||attachments[key]);
}
function checkValue(stageId,index){const values=project.stageChecks&&project.stageChecks[String(stageId)];return Boolean(values&&values[index])}
function stageState(stage){const criteriaReady=stage.criteria.every((_,i)=>checkValue(stage.id,i)),docsReady=stage.docs.every(([key])=>docReady(key));return{criteriaReady,docsReady,ready:criteriaReady&&docsReady}}
function allRequiredKeys(){return [...new Set(STAGES.flatMap(stage=>stage.docs.map(([key])=>key)))]}
function completeness(){const keys=allRequiredKeys(),done=keys.filter(docReady).length;return keys.length?done/keys.length*100:0}
function stageOverview(){
  const stage=stageById(currentStage()),state=stageState(stage),done=stage.criteria.filter((_,i)=>checkValue(stage.id,i)).length,docs=stage.docs.filter(([key])=>docReady(key)).length,total=stage.criteria.length+stage.docs.length,progress=Math.round((done+docs)/Math.max(total,1)*100);
  $('current-stage-overview').innerHTML=`<div class="stage-overview-head"><div><span>Этап ${stage.id} из ${STAGES.length}</span><strong>${esc(stage.name)}</strong></div><span class="stage-duration">${esc(stage.duration)}</span></div><div class="stage-overview-progress"><span style="width:${progress}%"></span></div><div class="stage-overview-meta"><span>Контрольные точки: ${done}/${stage.criteria.length}</span><span>Документы: ${docs}/${stage.docs.length}</span><span>Готовность: ${progress}%</span></div><div class="stage-result"><b>Результат:</b> ${esc(stage.result)}</div>${state.ready?'<div class="stage-ready-note">Все обязательные условия этапа выполнены.</div>':''}`;
}
function nextAction(){
  const stage=stageById(currentStage()),state=stageState(stage);let title='',href=`passport.html?location=${encodeURIComponent(id)}&tab=stages`;
  const missingCriterion=stage.criteria.find((_,i)=>!checkValue(stage.id,i));
  const missingDoc=stage.docs.find(([key])=>!docReady(key));
  if(missingCriterion)title=missingCriterion;
  else if(missingDoc){title='Добавить: '+missingDoc[1];const doc=DOCS.find(d=>d.key===missingDoc[0]);if(doc?.kind==='editor')href=`${doc.href}?location=${encodeURIComponent(id)}`;else href=`passport.html?location=${encodeURIComponent(id)}&tab=documents`}
  else if(stage.id<STAGES.length)title='Завершить этап и перейти к «'+STAGES[stage.id].name+'»';
  else title='Завершить проект и передать объект в эксплуатацию';
  $('next-step').innerHTML=`<strong>Следующее действие</strong><p>${esc(title)}</p><a class="wf-btn small primary" href="${href}">Открыть</a>`;
}
function workflowSummary(){
  const chain=[
    {name:'Расчётная спецификация',ready:docReady('spec'),version:project.specVersion||0,href:`source-specification.html?location=${encodeURIComponent(id)}`,outdated:false},
    {name:'Смета',ready:docReady('estimate'),version:project.estimateVersion||0,href:`specification.html?location=${encodeURIComponent(id)}`,outdated:Boolean(project.estimateOutdated)},
    {name:'КП',ready:docReady('proposal'),version:project.proposalVersion||0,href:`proposal.html?location=${encodeURIComponent(id)}`,outdated:Boolean(project.proposalOutdated)}
  ];
  $('document-chain').innerHTML=chain.map((item,index)=>`${index?'<div class="chain-arrow">→</div>':''}<a class="chain-card ${item.ready?'ready':''} ${item.outdated?'outdated':''}" href="${item.href}"><span>${index+1}</span><div><h4>${item.name}</h4><p>${item.outdated?'Требует обновления':item.ready?'Версия v'+item.version:'Документ не создан'}</p></div><b>${item.outdated?'!':item.ready?'✓':'○'}</b></a>`).join('');
}
function summary(){
  stageOverview();nextAction();workflowSummary();
  const payments=Array.isArray(project.paymentSchedule)?project.paymentSchedule:[],paid=payments.reduce((s,p)=>s+(Number(p.actual)||0),0),plan=payments.reduce((s,p)=>s+(Number(p.planned)||0),0);
  $('overview-stats').innerHTML=[['Итого по смете',money(project.total)],['Комплектность документов',Math.round(completeness())+'%'],['Плановая дата открытия',project.openingDate?date(project.openingDate):'Не указана'],['Оплачено',money(paid)],['Ответственный',project.managerName||'Не назначен'],['План платежей',money(plan)]].map(([label,value])=>`<div class="overview-stat"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`).join('');
  calculations();proposalSummary();financeSummary();
}
function calculations(){
  const specReady=docReady('spec'),estimateReady=docReady('estimate');
  $('spec-state').textContent=project.specVersion?'v'+project.specVersion:specReady?'Черновик':'Не создана';$('spec-state').className='calculation-state '+(specReady?'ready':'');
  $('estimate-state').textContent=project.estimateOutdated?'Требует обновления':project.estimateVersion?'v'+project.estimateVersion:estimateReady?'Черновик':'Не создана';$('estimate-state').className='calculation-state '+(project.estimateOutdated?'outdated':estimateReady?'ready':'');
  $('spec-meta').innerHTML=`<span>Версий: ${(project.specVersions||[]).length}</span><span>${project.specName?esc(project.specName):'Исходный файл не указан'}</span>`;
  $('estimate-meta').innerHTML=`<span>Итого: ${money(project.total)}</span><span>Версий: ${(project.estimateVersions||[]).length}</span>`;
  $('open-specification').href=`source-specification.html?location=${encodeURIComponent(id)}`;$('open-estimate').href=`specification.html?location=${encodeURIComponent(id)}`;
}
function proposalSummary(){const ready=docReady('proposal');$('proposal-state').textContent=project.proposalOutdated?'Требует обновления':project.proposalVersion?'v'+project.proposalVersion:ready?'Черновик':'Не создано';$('proposal-state').className='calculation-state '+(project.proposalOutdated?'outdated':ready?'ready':'');$('proposal-meta').innerHTML=`<span>Связано со сметой: v${project.proposalEstimateVersion||project.estimateVersion||0}</span><span>Версий: ${(project.proposalVersions||[]).length}</span>`;$('open-proposal').href=`proposal.html?location=${encodeURIComponent(id)}`}
function financeSummary(){const list=Array.isArray(project.paymentSchedule)?project.paymentSchedule:[],planned=list.reduce((s,p)=>s+(Number(p.planned)||0),0),paid=list.reduce((s,p)=>s+(Number(p.actual)||0),0),remaining=Math.max(0,planned-paid);$('object-finance-summary').innerHTML=[['Бюджет по смете',money(project.total)],['План платежей',money(planned)],['Оплачено',money(paid)],['Остаток',money(remaining)]].map(([label,value])=>`<div><strong>${value}</strong><span>${label}</span></div>`).join('')}
function renderStages(){
  const root=$('stages-root'),active=currentStage();
  root.innerHTML=STAGES.map(stage=>{const state=stageState(stage),done=stage.criteria.filter((_,i)=>checkValue(stage.id,i)).length,docs=stage.docs.filter(([key])=>docReady(key)).length,position=stage.id<active?'complete':stage.id===active?'current':'future';return `<article class="stage-card ${position}"><div class="stage-card-top"><div class="stage-number">${stage.id}</div><div class="stage-title"><span>${stage.id<active?'Завершённый этап':stage.id===active?'Текущий этап':'Следующий этап'}</span><h3>${esc(stage.name)}</h3></div><div class="stage-tags"><span>${esc(stage.duration)}</span><span>${done}/${stage.criteria.length} точек</span><span>${docs}/${stage.docs.length} документов</span></div></div><div class="stage-card-grid"><div><h4>Контрольные точки</h4><div class="stage-checks">${stage.criteria.map((text,index)=>`<label><input type="checkbox" data-stage-check="${stage.id}" data-index="${index}" ${checkValue(stage.id,index)?'checked':''}><span>${esc(text)}</span></label>`).join('')}</div></div><div><h4>Обязательные результаты</h4><div class="stage-docs">${stage.docs.map(([key,title])=>`<a class="stage-doc ${docReady(key)?'ready':'missing'}" href="${docLink(key)}"><span>${docReady(key)?'✓':'○'}</span><b>${esc(title)}</b></a>`).join('')}</div></div></div><div class="stage-card-bottom"><div class="stage-result-text ${state.ready?'ready':''}"><b>Результат этапа:</b> ${esc(stage.result)}</div>${stage.id===active&&stage.id<STAGES.length?`<button class="wf-btn small primary" data-next-stage="${stage.id+1}" ${state.ready?'':'disabled'}>Завершить этап</button>`:''}${stage.id===active&&stage.id===STAGES.length?`<button class="wf-btn small primary" data-complete-project ${state.ready?'':'disabled'}>Закрыть проект</button>`:''}</div></article>`}).join('');
  root.querySelectorAll('[data-stage-check]').forEach(input=>input.onchange=()=>{const key=String(input.dataset.stage),values=Array.isArray(project.stageChecks[key])?project.stageChecks[key]:[];values[Number(input.dataset.index)]=input.checked;project.stageChecks[key]=values;dirty=true;renderStages();summary()});
  root.querySelectorAll('[data-next-stage]').forEach(button=>button.onclick=()=>changeStage(Number(button.dataset.nextStage),true));
  root.querySelectorAll('[data-complete-project]').forEach(button=>button.onclick=()=>{project.status='Завершён';project.actualOpeningDate=project.actualOpeningDate||new Date().toISOString().slice(0,10);save();msg('ok','Проект закрыт и объект отмечен как завершённый.')});
}
function docLink(key){if(key==='gantt')return`passport.html?location=${encodeURIComponent(id)}&tab=schedule`;if(key==='payments')return`passport.html?location=${encodeURIComponent(id)}&tab=finance`;const doc=DOCS.find(d=>d.key===key);if(doc?.kind==='editor')return`${doc.href}?location=${encodeURIComponent(id)}`;return`passport.html?location=${encodeURIComponent(id)}&tab=documents`}
async function loadAttachments(){for(const d of DOCS)attachments[d.key]=await W.getAttachment(id,d.key);for(const key of EXTRA_DOWNLOADS)attachments[key]=await W.getAttachment(id,key);documents();renderStages();summary()}
function docName(doc){const a=attachments[doc.key];return a&&a.name||project[doc.key+'Name']||doc.key==='spec'&&project.specName||doc.key==='estimate'&&project.estimateName||doc.key==='proposal'&&project.proposalName||doc.key==='plan'&&project.planName||''}
function documents(){
  const root=$('documents-grid');
  root.innerHTML=STAGES.map(stage=>{const docs=DOCS.filter(doc=>doc.stage===stage.id);if(!docs.length)return'';return`<section class="document-stage-group"><div class="document-stage-head"><span>${stage.id}</span><strong>${esc(stage.name)}</strong></div><div class="document-stage-cards">${docs.map(doc=>{const a=attachments[doc.key],name=docName(doc),ready=docReady(doc.key),edited=doc.key==='spec'&&attachments['spec-edited'],pdf=doc.key==='proposal'&&attachments['proposal-pdf'];return`<article class="doc-card ${ready?'ready':''}"><div class="doc-card-status">${ready?'✓ Актуален':'Не добавлен'}</div><h3>${esc(doc.title)}</h3><p>${esc(doc.desc)}</p><div class="doc-file">${name?'Файл: '+esc(name):doc.kind==='editor'&&ready?'Данные сохранены в программе.':'Файл пока не добавлен.'}</div><div class="doc-actions">${doc.kind==='editor'?`<a class="wf-btn small primary" href="${doc.href}?location=${encodeURIComponent(id)}">${ready?'Редактировать':'Сформировать'}</a>`:`<span class="doc-upload"><button class="wf-btn small primary">${ready?'Заменить':'Загрузить'}</button><input data-upload="${doc.key}" type="file"></span>`}<button class="wf-btn small" data-download="${doc.key}" ${a?'':'disabled'}>Скачать</button>${edited?'<button class="wf-btn small" data-download="spec-edited">Изменённая версия</button>':''}${pdf?'<button class="wf-btn small" data-download="proposal-pdf">PDF</button>':''}</div></article>`}).join('')}</div></section>`}).join('');
  root.querySelectorAll('[data-upload]').forEach(input=>input.onchange=async()=>{const file=input.files&&input.files[0];if(!file)return;const key=input.dataset.upload;await W.saveAttachment(id,key,file,file.name);attachments[key]={blob:file,name:file.name};project[key+'Name']=file.name;dirty=true;documents();renderStages();summary();msg('ok','Документ добавлен. Сохраните объект, чтобы зафиксировать изменение.')});
  root.querySelectorAll('[data-download]').forEach(button=>button.onclick=()=>{const a=attachments[button.dataset.download];if(a&&a.blob)W.download(a.blob,a.name||button.dataset.download)});
}
function gantt(){const list=Array.isArray(project.gantt)?project.gantt:[];$('gantt-list').innerHTML=list.length?list.map((row,index)=>{const days=row.start&&row.end?Math.max(1,Math.ceil((new Date(row.end)-new Date(row.start))/86400000)+1):0;return`<div class="gantt-row"><input data-g="${index}" data-k="name" value="${esc(row.name||'Работа')}"><input data-g="${index}" data-k="start" type="date" value="${esc(row.start||'')}"><input data-g="${index}" data-k="end" type="date" value="${esc(row.end||'')}"><div class="gantt-track"><div class="gantt-bar">${days?days+' дн.':'Укажите даты'}</div></div><button class="row-delete delete-stage" data-gdel="${index}">×</button></div>`}).join(''):'<div class="empty-passport">Работы пока не добавлены.</div>';$('gantt-list').querySelectorAll('[data-k]').forEach(input=>input.onchange=()=>{project.gantt[Number(input.dataset.g)][input.dataset.k]=input.value;dirty=true;gantt();renderStages();summary()});$('gantt-list').querySelectorAll('[data-gdel]').forEach(button=>button.onclick=()=>{project.gantt.splice(Number(button.dataset.gdel),1);dirty=true;gantt();renderStages();summary()})}
function payments(){const list=Array.isArray(project.paymentSchedule)?project.paymentSchedule:[];$('payments-root').innerHTML=list.length?list.map((row,index)=>`<tr><td><input data-pay="${index}" data-k="name" value="${esc(row.name||'Платёж')}"></td><td><input data-pay="${index}" data-k="planDate" type="date" value="${esc(row.planDate||'')}"></td><td><input data-pay="${index}" data-k="planned" type="number" value="${esc(row.planned||0)}"></td><td><input data-pay="${index}" data-k="actualDate" type="date" value="${esc(row.actualDate||'')}"></td><td><input data-pay="${index}" data-k="actual" type="number" value="${esc(row.actual||0)}"></td><td><select data-pay="${index}" data-k="status">${['Запланирован','На согласовании','Частично оплачен','Оплачен','Просрочен'].map(x=>`<option ${row.status===x?'selected':''}>${x}</option>`).join('')}</select></td><td><button class="row-delete" data-pdel="${index}">×</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty-passport">Платежи пока не добавлены.</td></tr>';$('payments-root').querySelectorAll('[data-k]').forEach(input=>input.onchange=()=>{const key=input.dataset.k;project.paymentSchedule[Number(input.dataset.pay)][key]=['planned','actual'].includes(key)?Number(input.value):input.value;dirty=true;renderStages();summary()});$('payments-root').querySelectorAll('[data-pdel]').forEach(button=>button.onclick=()=>{project.paymentSchedule.splice(Number(button.dataset.pdel),1);dirty=true;payments();renderStages();summary()})}
function historyRows(){const rows=[];(project.specVersions||[]).forEach(v=>rows.push([v.createdAt,'Расчётная спецификация сохранена','v'+v.version]));(project.estimateVersions||[]).forEach(v=>rows.push([v.createdAt,'Создана версия сметы','v'+v.version+' · '+money(v.total)]));(project.proposalVersions||[]).forEach(v=>rows.push([v.createdAt,'Создана версия КП','v'+v.version]));if(project.createdAt)rows.push([project.createdAt,'Объект создан','Система']);if(project.updatedAt)rows.push([project.updatedAt,'Последнее изменение','Система']);if(P)(P.read().activity||[]).filter(a=>String(a.projectId)===String(id)).forEach(a=>rows.push([a.createdAt,a.text,a.actorName||'Пользователь']));rows.sort((a,b)=>String(b[0]).localeCompare(String(a[0])));$('history-root').innerHTML=rows.length?rows.map(row=>`<tr><td>${date(row[0])}</td><td>${esc(row[1])}</td><td>${esc(row[2])}</td></tr>`).join(''):'<tr><td colspan="3">История пока пуста.</td></tr>'}
function collect(){const stage=Number($('current-stage').value)||1,patch={address:$('address').value.trim(),stage,phase:Math.min(stage,5),status:$('status').value,stageChecks:project.stageChecks||{},phaseChecks:project.stageChecks||{},gantt:project.gantt||[],paymentSchedule:project.paymentSchedule||[]};document.querySelectorAll('#passport-form [data-field]').forEach(input=>patch[input.dataset.field]=input.type==='number'?Number(input.value):input.value);DOCS.filter(doc=>doc.kind==='upload').forEach(doc=>{if(project[doc.key+'Name'])patch[doc.key+'Name']=project[doc.key+'Name']});return patch}
function save(){const before=project.address;project=W.updateProject(id,collect());if(P)P.activity(id,'project',before?'Рабочее пространство объекта обновлено':'Объект создан');localStorage.setItem('slogi_active_project_v1',id);dirty=false;render();msg('ok','Данные объекта сохранены.')}
function changeStage(next,persist){project.stage=Math.min(6,Math.max(1,Number(next)||1));project.phase=Math.min(project.stage,5);$('current-stage').value=String(project.stage);dirty=true;if(persist){project=W.updateProject(id,{stage:project.stage,phase:project.phase,stageChecks:project.stageChecks||{},phaseChecks:project.stageChecks||{}});if(P)P.activity(id,'stage',`Объект переведён на этап «${stageById(project.stage).name}»`);dirty=false}renderStages();summary();msg('ok','Текущий этап: '+stageById(project.stage).name+'.')}
async function downloadAll(){msg('','Собираю архив…');const entries=[],encoder=new TextEncoder(),keys=[...DOCS.map(d=>d.key),...EXTRA_DOWNLOADS];for(const key of keys){const a=attachments[key]||await W.getAttachment(id,key);if(a&&a.blob)entries.push({name:a.name||key,data:new Uint8Array(await a.blob.arrayBuffer())})}entries.push({name:'Паспорт объекта.json',data:encoder.encode(JSON.stringify(project,null,2))});const blob=await OfficeZip.zip(entries),zip=new Blob([await blob.arrayBuffer()],{type:'application/zip'});W.download(zip,W.safeName('Объект '+(project.address||id))+'.zip');msg('ok','Архив подготовлен.')}
function activateTab(name,updateUrl){const tab=document.querySelector(`.passport-tab[data-tab="${name}"]`)||document.querySelector('.passport-tab');document.querySelectorAll('.passport-tab').forEach(x=>x.classList.toggle('active',x===tab));document.querySelectorAll('.passport-pane').forEach(x=>x.classList.toggle('active',x.dataset.pane===tab.dataset.tab));if(updateUrl){const params=new URLSearchParams(location.search);if(tab.dataset.tab==='overview')params.delete('tab');else params.set('tab',tab.dataset.tab);history.replaceState({},'',`passport.html?${params.toString()}`)}}
function tabs(){document.querySelectorAll('.passport-tab').forEach(button=>button.onclick=()=>activateTab(button.dataset.tab,true));activateTab(new URLSearchParams(location.search).get('tab')||'overview',false)}
function render(){$('address').value=project.address||'';statuses();stagesSelect();form();summary();renderStages();gantt();payments();historyRows();documents()}
async function init(){project=W.getProject(id);createIfNeeded();project.stage=Number(project.stage||project.phase)||1;project.phase=Math.min(project.stage,5);project.stageChecks=project.stageChecks&&typeof project.stageChecks==='object'?project.stageChecks:(project.phaseChecks&&typeof project.phaseChecks==='object'?project.phaseChecks:{});render();tabs();$('address').oninput=()=>dirty=true;$('status').onchange=()=>dirty=true;$('current-stage').onchange=()=>changeStage(Number($('current-stage').value),false);$('save-passport').onclick=save;$('download-all').onclick=downloadAll;$('add-stage').onclick=()=>{project.gantt=project.gantt||[];project.gantt.push({name:'Новая работа',start:'',end:''});dirty=true;gantt();renderStages();summary()};$('add-payment').onclick=()=>{project.paymentSchedule=project.paymentSchedule||[];project.paymentSchedule.push({name:'Новый платёж',planDate:'',planned:0,actualDate:'',actual:0,status:'Запланирован'});dirty=true;payments();renderStages();summary()};await loadAttachments()}
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue=''}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
