(function(){'use strict';
const P=window.SlogiPro; const $=id=>document.getElementById(id); const esc=v=>window.SlogiUI?SlogiUI.esc(v):String(v||'').replace(/[&<>"']/g,'');
let projects=[],features=[],activeCluster='',map=null,polygons=[],markers=[];
const mineOnly=new URLSearchParams(location.search).get('mine')==='1';
const norm=v=>String(v||'').trim().toLowerCase().replace(/ё/g,'е');
const statusOf=p=>p.status||p.projectStatus||'Новый';
const STAGES=['Первичная оценка','Замеры и расчёт','Согласование аренды','Подготовка к ремонту','Ремонт','Открытие'];
const stageOf=p=>STAGES[Math.min(6,Math.max(1,Number(p.stage||p.phase)||1))-1];
function read(){projects=(P?P.readLocations():JSON.parse(localStorage.getItem('slogi_locations_v1')||'[]')).filter(p=>p&&p.id&&!p.deletedAt);features=(window.SLOGI_CLUSTERS_GEOJSON&&window.SLOGI_CLUSTERS_GEOJSON.features)||[]}
function matches(p){const q=norm($('object-search').value),cl=norm($('cluster-filter').value),st=$('status-filter').value,actor=P&&P.actor?P.actor():{id:'',name:''};const pc=norm(p.clusterName),mine=!mineOnly||String(p.managerId||'')===String(actor.id||'')||norm(p.managerName).includes(norm(actor.name));return mine&&(!q||norm(p.address).includes(q))&&(!cl||pc===cl||pc.includes(cl)||cl.includes(pc))&&(!st||statusOf(p)===st)}
function populate(){const names=[...new Set([...features.map(f=>f.properties&&f.properties.name),...projects.map(p=>p.clusterName)].filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ru'));$('cluster-filter').innerHTML='<option value="">Все кластеры</option>'+names.map(n=>`<option>${esc(n)}</option>`).join('');const statuses=[...new Set(projects.map(statusOf))];$('status-filter').innerHTML='<option value="">Все статусы</option>'+statuses.map(n=>`<option>${esc(n)}</option>`).join('')}
function renderKpis(){const repair=projects.filter(p=>Math.min(6,Math.max(1,Number(p.stage||p.phase)||1))>=4).length,newObjects=projects.filter(p=>statusOf(p)==='Новый').length,total=projects.reduce((x,p)=>x+(Number(p.total)||0),0);$('portfolio-kpis').innerHTML=[[''+projects.length,'Объектов в портфеле'],[''+repair,'На этапе ремонта'],[''+newObjects,'Новых объектов'],[(P?P.formatMoney(total):Math.round(total).toLocaleString('ru-RU')+' ₽'),'По сохранённым сметам']].map(x=>`<div class="portfolio-kpi"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}
function filtered(){return projects.filter(matches)}
function renderCards(){const list=filtered();$('portfolio-summary').textContent=`Показано: ${list.length} из ${projects.length}`;$('object-panel-title').textContent=activeCluster?activeCluster:(mineOnly?'Мои объекты':'Все объекты');$('object-panel-subtitle').textContent=activeCluster?`Все объекты кластера · ${list.length}`:(mineOnly?'Объекты, где вы назначены ответственным':'Сохранённые адреса');$('object-cards').innerHTML=list.length?list.map(p=>`<a class="object-card" href="passport.html?location=${encodeURIComponent(p.id)}"><h4>${esc(p.address||'Объект без адреса')}</h4><div class="object-card-meta"><span class="object-pill">${esc(p.clusterName||'Кластер не указан')}</span><span class="object-pill object-phase-pill">${esc(stageOf(p))}</span><span class="object-pill">${esc(statusOf(p))}</span></div><div class="object-card-total">${P?P.formatMoney(p.total||0):Math.round(p.total||0).toLocaleString('ru-RU')+' ₽'}</div></a>`).join(''):'<div class="empty-objects">В выбранном кластере объектов пока нет.</div>';renderMarkers();stylePolygons()}
function renderAttention(){const items=projects.filter(p=>!['Завершён','Архив'].includes(statusOf(p))).slice(0,5).map(p=>[p.address||'Объект без адреса',stageOf(p)+' · '+statusOf(p),'passport.html?location='+encodeURIComponent(p.id)]);$('attention-list').innerHTML=items.length?items.map(x=>`<div class="attention-item"><div><strong>${esc(x[0])}</strong><span>${esc(x[1])}</span></div><a href="${x[2]}">Открыть</a></div>`).join(''):'<div class="portfolio-empty-note">Активных объектов нет.</div>'}
function featureCoords(f){const g=f.geometry||{},conv=ring=>ring.map(p=>[p[1],p[0]]);if(g.type==='Polygon')return g.coordinates.map(conv);if(g.type==='MultiPolygon')return g.coordinates.map(poly=>poly.map(conv));return null}
function featureBounds(f){if(f.bbox)return[[f.bbox[1],f.bbox[0]],[f.bbox[3],f.bbox[2]]];const pts=[];function walk(x){if(Array.isArray(x)&&typeof x[0]==='number')pts.push([x[1],x[0]]);else if(Array.isArray(x))x.forEach(walk)}walk(f.geometry&&f.geometry.coordinates);if(!pts.length)return null;return[[Math.min(...pts.map(p=>p[0])),Math.min(...pts.map(p=>p[1]))],[Math.max(...pts.map(p=>p[0])),Math.max(...pts.map(p=>p[1]))]]}
function addFeature(f){const name=f.properties&&f.properties.name,coords=featureCoords(f);if(!name||!coords)return;const opts={fillColor:'#4B6E73',strokeColor:'#37545A',strokeWidth:1.5,fillOpacity:.16};const add=geometry=>{const poly=new ymaps.Polygon(geometry,{hintContent:name,clusterName:name},opts);poly.events.add('click',()=>selectCluster(name,f));map.geoObjects.add(poly);polygons.push(poly)};if(f.geometry.type==='Polygon')add(coords);else coords.forEach(add)}
function stylePolygons(){polygons.forEach(poly=>{const name=poly.properties.get('clusterName');poly.options.set({fillOpacity:activeCluster ? (norm(name)===norm(activeCluster) ? .38 : .06) : .16,strokeWidth:activeCluster&&norm(name)===norm(activeCluster)?3:1.5,fillColor:activeCluster&&norm(name)===norm(activeCluster)?'#E19B2D':'#4B6E73',strokeColor:activeCluster&&norm(name)===norm(activeCluster)?'#C97F16':'#37545A'})})}
function geoOf(p){const g=p.geo;if(Array.isArray(g)&&g.length>=2)return g; if(g&&Number.isFinite(Number(g.lat))&&Number.isFinite(Number(g.lng)))return[Number(g.lat),Number(g.lng)];if(g&&Array.isArray(g.coordinates))return g.coordinates;return null}
function renderMarkers(){if(!map)return;markers.forEach(m=>map.geoObjects.remove(m));markers=[];filtered().forEach(p=>{const c=geoOf(p);if(!c)return;const m=new ymaps.Placemark(c,{balloonContentHeader:esc(p.address),balloonContentBody:`${esc(p.clusterName||'')}<br><a href="passport.html?location=${encodeURIComponent(p.id)}">Открыть объект</a>`},{preset:'islands#orangeCircleDotIcon'});map.geoObjects.add(m);markers.push(m)})}
function selectCluster(name,f){activeCluster=name;$('cluster-filter').value=name;$('object-search').value='';$('status-filter').value='';renderCards();const b=featureBounds(f);if(map&&b)map.setBounds(b,{checkZoomRange:true,zoomMargin:36})}
function loadYandex(){return new Promise((resolve,reject)=>{if(window.ymaps)return ymaps.ready(resolve);const key=window.SLOGI_CONFIG&&SLOGI_CONFIG.yandexMapsApiKey;const s=document.createElement('script');s.src='https://api-maps.yandex.ru/2.1/?lang=ru_RU'+(key?'&apikey='+encodeURIComponent(key):'');s.async=true;s.onload=()=>ymaps.ready(resolve);s.onerror=()=>reject(new Error('Карта недоступна'));document.head.appendChild(s);setTimeout(()=>reject(new Error('Превышено время загрузки карты')),15000)})}
async function initMap(){try{await loadYandex();map=new ymaps.Map('portfolio-map',{center:[55.7558,37.6176],zoom:10,controls:['zoomControl','fullscreenControl']},{suppressMapOpenBlock:true});features.forEach(addFeature);renderMarkers();$('map-loading').classList.add('hidden')}catch(e){$('map-loading').innerHTML='<strong>Не удалось загрузить Яндекс Карты</strong><span>Карточки объектов остаются доступными. Проверьте ключ API и разрешённый домен.</span>';$('map-message').textContent='Карта не загрузилась: '+e.message}}
function bind(){['object-search','status-filter'].forEach(id=>$(id).addEventListener(id==='object-search'?'input':'change',()=>{activeCluster=$('cluster-filter').value;renderCards()}));$('cluster-filter').addEventListener('change',()=>{activeCluster=$('cluster-filter').value;renderCards();if(!activeCluster&&map)map.setCenter([55.7558,37.6176],10)})}
function init(){read();populate();renderKpis();renderCards();renderAttention();bind();requestAnimationFrame(initMap)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.addEventListener('slogi:locations-updated',()=>{read();populate();renderKpis();renderCards()});
})();
