(function(){
'use strict';
const KEY='slogi_professional_state_v2', LOCATIONS_KEY='slogi_locations_v1', VERSION=2;
const now=()=>new Date().toISOString();
const uid=(p='id')=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);
const clone=v=>JSON.parse(JSON.stringify(v));
const parse=(v,f)=>{try{return JSON.parse(v)}catch(e){return f}};
const readLocations=()=>{const d=parse(localStorage.getItem(LOCATIONS_KEY)||'[]',[]);return Array.isArray(d)?d:[]};
const writeLocations=a=>localStorage.setItem(LOCATIONS_KEY,JSON.stringify(a));
const defaults=()=>({version:VERSION,organization:{name:'СЛОГИ',workspace:'Управление объектами',currency:'RUB',timezone:'Europe/Moscow'},members:[
{id:'member-maria',name:'Мария Козлова',position:'Руководитель проекта',role:'Администратор',email:'',status:'active'},
{id:'member-estimator',name:'Сметчик',position:'Сметное сопровождение',role:'Сметчик',email:'',status:'active'},
{id:'member-designer',name:'Дизайнер / замерщик',position:'Проектирование и замеры',role:'Проектировщик',email:'',status:'active'},
{id:'member-finance',name:'Финансовый специалист',position:'Оплаты и документы',role:'Финансы',email:'',status:'active'}],
tasks:[],payments:[],approvals:[],documentVersions:[],estimateVersions:[],priceCatalog:[],templates:[{id:'tpl-standard',type:'Проект',name:'Стандартный объект',description:'Замеры → смета → согласование → строительство',status:'Активен',createdAt:now()},{id:'tpl-fast',type:'Проект',name:'Быстрый ремонт',description:'Сокращённый маршрут и контрольные точки',status:'Активен',createdAt:now()},{id:'tpl-proposal',type:'КП',name:'Корпоративное коммерческое предложение',description:'Основной шаблон КП СЛОГИ',status:'Активен',createdAt:now()}],contracts:[],contractors:[],comparisons:[],activity:[],notifications:[],risks:[],comments:[],
settings:{statuses:['Новый','Замеры','Расчёт сметы','На согласовании','Согласован','Строительство','Завершён','Архив'],notifications:{deadlines:true,approvals:true,payments:true,budget:true,staleProjects:true},staleDays:7,defaultReserve:10,twoFactor:false,requireChangeReason:true},trash:{projects:[]},updatedAt:now()});
function normalize(s){const b=defaults(),o=Object.assign(b,s&&typeof s==='object'?s:{});['members','tasks','payments','approvals','documentVersions','estimateVersions','priceCatalog','templates','contracts','contractors','comparisons','activity','notifications','risks','comments'].forEach(k=>{if(!Array.isArray(o[k]))o[k]=[]});o.settings=Object.assign(b.settings,o.settings||{});o.settings.notifications=Object.assign(b.settings.notifications,(o.settings||{}).notifications||{});o.organization=Object.assign(b.organization,o.organization||{});o.trash=Object.assign({projects:[]},o.trash||{});if(!Array.isArray(o.trash.projects))o.trash.projects=[];o.version=VERSION;return o}
function read(){return normalize(parse(localStorage.getItem(KEY)||'null',null)||defaults())}
function write(s,r){const n=normalize(s);n.updatedAt=now();localStorage.setItem(KEY,JSON.stringify(n));window.dispatchEvent(new CustomEvent('slogi:professional-state',{detail:{state:clone(n),reason:r||'update'}}));return n}
function actor(){const u=window.SlogiCloud&&window.SlogiCloud.user,m=u&&u.user_metadata||{};return{id:u&&u.id||'member-maria',name:m.full_name||m.name||'Мария Козлова'}}
function projectName(id){const p=readLocations().find(x=>String(x.id)===String(id));return p?p.address:'Объект'}
function activity(projectId,type,text,meta){const s=read(),a=actor();s.activity.unshift({id:uid('act'),projectId:projectId||'',type:type||'update',text:String(text||''),actorId:a.id,actorName:a.name,createdAt:now(),meta:meta||{}});s.activity=s.activity.slice(0,500);write(s,'activity')}
function enrichProjectState(s,p){if(!p||!p.id)return false;let c=false;const projectId=String(p.id),due=d=>{const x=new Date();x.setDate(x.getDate()+d);return x.toISOString().slice(0,10)};
if(!s.tasks.some(x=>String(x.projectId)===projectId)){s.tasks.push({id:uid('task'),projectId:p.id,title:'Проверить комплектность исходных данных',ownerId:'member-maria',dueDate:due(2),priority:'Высокий',status:'Новая',stage:'Исходные данные',checklist:[],createdAt:now(),updatedAt:now()},{id:uid('task'),projectId:p.id,title:'Актуализировать смету и сроки',ownerId:'member-estimator',dueDate:due(5),priority:'Средний',status:'В работе',stage:'Расчёт сметы',checklist:[],createdAt:now(),updatedAt:now()});c=true}
if(!s.approvals.some(x=>String(x.projectId)===projectId)){s.approvals.push({id:uid('approval'),projectId:p.id,entityType:'Смета',title:'Согласование базовой сметы',version:'v1',status:'Черновик',requestedBy:'member-maria',approverId:'member-finance',dueDate:'',comment:'',createdAt:now(),updatedAt:now()});c=true}
if(!s.payments.some(x=>String(x.projectId)===projectId)&&Array.isArray(p.paymentSchedule)&&p.paymentSchedule.length){p.paymentSchedule.forEach(row=>s.payments.push({id:uid('pay'),projectId:p.id,category:'Работы',title:row.name||'Платёж по объекту',amount:Number(row.planned)||0,plannedDate:row.planDate||'',status:Number(row.actual)>0?'Оплачен':'Запланирован',paidDate:row.actualDate||'',actualAmount:Number(row.actual)||0,createdAt:now(),updatedAt:now()}));c=true}
if(!s.documentVersions.some(x=>String(x.projectId)===projectId)){const imported=[['План',p.planName],['Спецификация',p.specName],['Смета',p.estimateName],['КП',p.proposalName]].filter(x=>x[1]);imported.forEach(([type,name])=>s.documentVersions.push({id:uid('doc'),projectId:p.id,type,name,version:'v1',status:'Актуальный',authorId:'member-maria',createdAt:p.updatedAt||now(),comment:'Импортировано из паспорта объекта'}));if(imported.length)c=true}
if(!s.risks.some(x=>String(x.projectId)===projectId)){s.risks.push({id:uid('risk'),projectId:p.id,title:'Не подтверждены сроки согласования',probability:'Средняя',impact:'Среднее',status:'Открыт',ownerId:'member-maria',mitigation:'Уточнить срок у согласующего',createdAt:now()});c=true}
return c}
function ensureProject(p){const s=read();if(enrichProjectState(s,p))write(s,'ensure-project')}
function ensureAllProjects(){const s=read();let changed=false;for(const p of readLocations().filter(x=>x&&x.id&&!x.deletedAt))changed=enrichProjectState(s,p)||changed;if(changed)write(s,'ensure-projects')}
function getProjectMeta(id){const s=read(),p=readLocations().find(x=>String(x.id)===String(id))||{},docs=s.documentVersions.filter(x=>x.projectId===id),present=new Set(docs.map(x=>x.type));if(p.planName)present.add('План');if(p.specName)present.add('Спецификация');if(p.estimateName)present.add('Смета');if(p.proposalName)present.add('КП');return{project:p,status:p.status||p.projectStatus||'Новый',managerId:p.managerId||'member-maria',tasks:s.tasks.filter(x=>x.projectId===id),docs,completeness:Math.round(['План','Спецификация','Смета','КП'].filter(x=>present.has(x)).length/4*100)}}
function upsert(collection,item,reason){const s=read(),list=s[collection];if(!Array.isArray(list))throw new Error('Unknown collection');const n=Object.assign({},item);if(!n.id)n.id=uid(collection.slice(0,4));if(!n.createdAt)n.createdAt=now();n.updatedAt=now();const i=list.findIndex(x=>x.id===n.id);if(i>=0)list[i]=Object.assign({},list[i],n);else list.unshift(n);write(s,reason||collection+'-upsert');return clone(n)}
function remove(collection,id){const s=read();s[collection]=(s[collection]||[]).filter(x=>x.id!==id);write(s,collection+'-remove')}
function updateProject(id,patch,reason){const l=readLocations(),i=l.findIndex(x=>String(x.id)===String(id));if(i<0)return null;const b=l[i],n=Object.assign({},b,patch,{updatedAt:now()});l[i]=n;writeLocations(l);const ch=Object.keys(patch).filter(k=>b[k]!==patch[k]);if(ch.length)activity(id,'project',reason||('Изменены параметры объекта: '+ch.join(', ')),{changes:ch});return n}
function softDeleteProject(p){if(!p||!p.id)return;const s=read();if(!s.trash.projects.some(x=>x.id===p.id))s.trash.projects.unshift(Object.assign({},p,{deletedAt:now()}));write(s,'project-soft-delete');activity(p.id,'delete','Объект перемещён в корзину')}
function restoreProject(id){const s=read(),p=s.trash.projects.find(x=>x.id===id);if(!p)return false;const c=Object.assign({},p);delete c.deletedAt;c.updatedAt=now();const l=readLocations();if(!l.some(x=>x.id===c.id))l.unshift(c);writeLocations(l);s.trash.projects=s.trash.projects.filter(x=>x.id!==id);write(s,'project-restore');activity(id,'restore','Объект восстановлен из корзины');return true}
function purgeProject(id){const s=read();s.trash.projects=s.trash.projects.filter(x=>x.id!==id);write(s,'project-purge')}
function notify(title,text,link,level){const s=read();s.notifications.unshift({id:uid('note'),title,text,link:link||'',level:level||'info',read:false,createdAt:now()});s.notifications=s.notifications.slice(0,100);write(s,'notification')}
const formatMoney=v=>Math.round(Number(v)||0).toLocaleString('ru-RU')+' ₽';
function formatDate(v,t){if(!v)return'—';const d=new Date(v);if(Number.isNaN(d.getTime()))return'—';return d.toLocaleDateString('ru-RU',t?{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'2-digit',year:'numeric'})}
function statusClass(v){const s=String(v||'').toLowerCase();if(/заверш|согласован|оплачен|утвержд|актив/.test(s))return'good';if(/просроч|отклон|риск|критич/.test(s))return'bad';if(/работ|согласовани|провер|ожида/.test(s))return'warn';return'neutral'}
function currentRole(){const u=window.SlogiCloud&&window.SlogiCloud.user,m=u&&u.user_metadata||{},explicit=String(m.role||m.access_level||'').trim();if(explicit)return explicit;const email=String(u&&u.email||'').toLowerCase(),member=read().members.find(x=>email&&String(x.email||'').toLowerCase()===email);return member&&member.role||'Администратор'}
function can(area,action){const role=currentRole(),admin=role==='Администратор',pm=role==='Руководитель проекта';if(admin)return true;if(action==='write'&&['Наблюдатель','Внешний пользователь'].includes(role))return false;if(['team.html','settings.html'].includes(area))return false;if(area==='finance.html')return pm||role==='Финансы';if(area==='contractors.html')return pm||['Финансы','Сметчик'].includes(role);if(area==='catalog.html')return pm||['Финансы','Сметчик','Проектировщик'].includes(role);if(area==='analytics.html')return role!=='Внешний пользователь';if(area==='approvals.html')return role!=='Внешний пользователь'||action!=='write';return true}
function exportData(){return{professional:read(),locations:readLocations()}}
function importData(p){if(p&&Array.isArray(p.locations))writeLocations(p.locations);if(p&&p.professional)write(p.professional,'import');return true}
window.SlogiPro={KEY,read,write,readLocations,writeLocations,ensureProject,ensureAllProjects,getProjectMeta,upsert,remove,updateProject,softDeleteProject,restoreProject,purgeProject,activity,notify,projectName,actor,currentRole,can,uid,now,formatMoney,formatDate,statusClass,exportData,importData};
ensureAllProjects();
})();
