(function(){
'use strict';
const P=window.SlogiPro;if(!P)return;
const esc=v=>String(v==null?'':v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const page=location.pathname.split('/').pop()||'index.html';

const pageTitles={
'index.html':['Все объекты','Управление объектами, сроками и бюджетом'],'passport.html':['Паспорт объекта','Параметры, документы, сроки и финансы'],'source-specification.html':['Спецификация','Исходные данные и позиции объекта'],'specification.html':['Смета объекта','Расчёт на основании подтверждённой спецификации'],'proposal.html':['Коммерческое предложение','Редактирование и выгрузка по фирменному шаблону'],'tasks.html':['Задачи','Контроль поручений и сроков'],'documents.html':['Документы','Версии и комплектность'],'approvals.html':['Согласования','Решения и замечания'],'finance.html':['Финансы','Бюджет, обязательства и оплаты'],'contractors.html':['Подрядчики','Контрагенты и сравнение предложений'],'catalog.html':['Справочники','Цены, версии смет и шаблоны'],'team.html':['Команда','Роли и уровни доступа'],'analytics.html':['Аналитика','Портфель объектов и показатели'],'settings.html':['Настройки','Рабочие процессы и безопасность']};
function normalizeHeader(){let header=document.querySelector('.site-header');if(!header){header=document.createElement('header');header.className='site-header';document.body.insertBefore(header,document.body.firstChild)}const account=document.getElementById('slogi-account-nav');const configured=pageTitles[page]||[(document.querySelector('.site-header h1')?.textContent||'СЛОГИ'),(document.querySelector('.site-header .subtitle')?.textContent||'')];header.innerHTML=`<div class="top"><div class="brand"><a class="logo-link" href="index.html" aria-label="СЛОГИ — все объекты"><div class="logo-word" aria-hidden="true"><span>С</span><span>Л</span><span>О</span><span>Г</span><span>И</span></div></a><div class="title-wrap"><h1>${esc(configured[0])}</h1><div class="subtitle">${esc(configured[1])}</div></div></div></div>`;if(account)header.querySelector('.top').appendChild(account);document.title='СЛОГИ — '+configured[0]}

const links=[['index.html','Портфель'],['tasks.html','Задачи'],['documents.html','Документы'],['approvals.html','Согласования'],['finance.html','Финансы'],['contractors.html','Подрядчики'],['catalog.html','Справочники'],['team.html','Команда'],['analytics.html','Аналитика'],['settings.html','Настройки']];
function active(file){if(page===file)return true;if(['passport.html','measure-passport.html','source-specification.html','specification.html','proposal.html'].includes(page)&&file==='index.html')return true;return false}
function addNav(){if(document.querySelector('.pro-nav'))return;const header=document.querySelector('.site-header');if(!header)return;const state=P.read(),unread=state.notifications.filter(x=>!x.read).length;const nav=document.createElement('nav');nav.className='pro-nav';nav.setAttribute('aria-label','Основная навигация');nav.innerHTML='<div class="pro-nav-inner">'+links.filter(([file])=>P.can(file,'view')).map(([file,label])=>`<a href="${file}" class="${active(file)?'active':''}">${label}</a>`).join('')+'<span class="pro-nav-spacer"></span><div class="pro-global-search-wrap"><input class="pro-global-search" id="pro-global-search" type="search" placeholder="Поиск по системе…" aria-label="Глобальный поиск"><button type="button" id="pro-global-search-btn">⌕</button></div><button type="button" class="pro-notification-btn" id="pro-notification-btn" aria-label="Уведомления">🔔'+(unread?`<span class="pro-notification-count">${unread}</span>`:'')+'</button></div>';header.appendChild(nav);header.classList.add('has-pro-nav');nav.querySelector('#pro-notification-btn').addEventListener('click',toggleDrawer);const input=nav.querySelector('#pro-global-search');nav.querySelector('#pro-global-search-btn').onclick=()=>runGlobalSearch(input.value);input.addEventListener('keydown',ev=>{if(ev.key==='Enter'){ev.preventDefault();runGlobalSearch(input.value)}})}
function ensureDrawer(){let d=document.getElementById('pro-drawer');if(d)return d;d=document.createElement('aside');d.id='pro-drawer';d.className='pro-drawer';d.innerHTML='<div class="pro-drawer-head"><div><strong>Уведомления</strong><div class="pro-muted" style="font-size:11px;margin-top:3px">Сроки, платежи и согласования</div></div><button class="pro-modal-close" id="pro-drawer-close" type="button">×</button></div><div class="pro-drawer-list" id="pro-drawer-list"></div>';document.body.appendChild(d);d.querySelector('#pro-drawer-close').addEventListener('click',()=>d.classList.remove('open'));return d}
function seedNotifications(){const s=P.read();if(s.notifications.length)return;const today=new Date().toISOString().slice(0,10),overdue=s.tasks.filter(t=>t.dueDate&&t.dueDate<today&&!['Готово','Отменена'].includes(t.status));if(overdue.length)s.notifications.push({id:P.uid('note'),title:'Просроченные задачи',text:`Требуют внимания: ${overdue.length}`,link:'tasks.html?filter=overdue',read:false,createdAt:P.now()});const pending=s.approvals.filter(a=>['На согласовании','Возвращено'].includes(a.status));if(pending.length)s.notifications.push({id:P.uid('note'),title:'Согласования',text:`Ожидают решения: ${pending.length}`,link:'approvals.html',read:false,createdAt:P.now()});if(s.notifications.length)P.write(s,'seed-notifications')}
function toggleDrawer(){seedNotifications();const d=ensureDrawer(),s=P.read(),list=d.querySelector('#pro-drawer-list');list.innerHTML=s.notifications.length?s.notifications.map(n=>`<div class="pro-note ${n.read?'':'unread'}" data-id="${n.id}"><h4>${esc(n.title)}</h4><p>${esc(n.text)}</p><time>${P.formatDate(n.createdAt,true)}</time>${n.link?`<a class="pro-btn small" style="margin-top:9px" href="${esc(n.link)}">Открыть</a>`:''}</div>`).join(''):'<div class="pro-empty">Новых уведомлений нет.</div>';d.classList.toggle('open');if(d.classList.contains('open')){s.notifications.forEach(n=>n.read=true);P.write(s,'notifications-read');const count=document.querySelector('.pro-notification-count');if(count)count.remove()}}
function runGlobalSearch(query){const q=String(query||'').trim().toLowerCase();if(q.length<2){toast('Введите минимум два символа');return}const s=P.read(),projects=P.readLocations();const results=[];projects.filter(x=>String(x.address||'').toLowerCase().includes(q)).forEach(x=>results.push({type:'Объект',title:x.address,sub:x.status||x.projectStatus||'Новый',href:'passport.html?location='+encodeURIComponent(x.id)}));s.tasks.filter(x=>String(x.title||'').toLowerCase().includes(q)).forEach(x=>results.push({type:'Задача',title:x.title,sub:P.projectName(x.projectId)+' · '+x.status,href:'tasks.html'}));s.documentVersions.filter(x=>String(x.name||'').toLowerCase().includes(q)||String(x.type||'').toLowerCase().includes(q)).forEach(x=>results.push({type:'Документ',title:x.name,sub:P.projectName(x.projectId)+' · '+x.version,href:'documents.html'}));s.contractors.filter(x=>String(x.name||'').toLowerCase().includes(q)||String(x.inn||'').toLowerCase().includes(q)).forEach(x=>results.push({type:'Подрядчик',title:x.name,sub:x.speciality||'',href:'contractors.html'}));s.priceCatalog.filter(x=>String(x.name||'').toLowerCase().includes(q)||String(x.code||'').toLowerCase().includes(q)).forEach(x=>results.push({type:'Справочник',title:x.name,sub:(x.category||'')+' · '+P.formatMoney(x.price),href:'catalog.html'}));s.comments.filter(x=>String(x.text||'').toLowerCase().includes(q)).forEach(x=>results.push({type:'Решение',title:x.text,sub:P.projectName(x.projectId),href:'passport.html?location='+encodeURIComponent(x.projectId)}));modal({title:'Результаты поиска',saveLabel:'Закрыть',body:results.length?'<div class="pro-stack">'+results.slice(0,30).map(r=>`<a class="pro-list-item" href="${esc(r.href)}" style="color:inherit;text-decoration:none"><div><div class="pro-list-title">${esc(r.title)}</div><div class="pro-list-sub">${esc(r.type)} · ${esc(r.sub)}</div></div><span class="pro-status neutral">Открыть</span></a>`).join('')+'</div>':'<div class="pro-empty">Ничего не найдено</div>',onSave:()=>true})}
function toast(text){let t=document.getElementById('pro-toast');if(!t){t=document.createElement('div');t.id='pro-toast';t.className='pro-toast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2600)}
function modal(opts){const backdrop=document.createElement('div');backdrop.className='pro-modal-backdrop open';backdrop.innerHTML=`<div class="pro-modal" role="dialog" aria-modal="true"><div class="pro-modal-head"><h2>${esc(opts.title||'')}</h2><button type="button" class="pro-modal-close">×</button></div><div class="pro-modal-body">${opts.body||''}</div><div class="pro-modal-actions"><button type="button" class="pro-btn" data-cancel>Отмена</button><button type="button" class="pro-btn primary" data-save>${esc(opts.saveLabel||'Сохранить')}</button></div></div>`;document.body.appendChild(backdrop);const close=()=>backdrop.remove();backdrop.querySelector('.pro-modal-close').onclick=close;backdrop.querySelector('[data-cancel]').onclick=close;backdrop.addEventListener('click',e=>{if(e.target===backdrop)close()});backdrop.querySelector('[data-save]').onclick=async()=>{const button=backdrop.querySelector('[data-save]');button.disabled=true;try{const result=opts.onSave&&opts.onSave(backdrop);const resolved=result&&typeof result.then==='function'?await result:result;if(resolved!==false)close()}finally{if(document.body.contains(button))button.disabled=false}};return backdrop}
function updateTitle(){const x=pageTitles[page];if(!x)return;const h=document.querySelector('.site-header h1'),sub=document.querySelector('.site-header .subtitle');if(h)h.textContent=x[0];if(sub)sub.textContent=x[1];document.title='СЛОГИ — '+x[0]}
window.SlogiUI={esc,toast,modal,page};
function syncShellHeight(header){const apply=()=>document.documentElement.style.setProperty('--app-shell-height',(header.offsetHeight||122)+'px');apply();if('ResizeObserver'in window){const ro=new ResizeObserver(()=>requestAnimationFrame(apply));ro.observe(header);header._slogiResizeObserver=ro}else window.addEventListener('resize',apply,{passive:true})}
function init(){normalizeHeader();addNav();updateTitle();const header=document.querySelector('.site-header');if(header)syncShellHeight(header)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.addEventListener('slogi:professional-state',()=>{const count=document.querySelector('.pro-notification-count'),unread=P.read().notifications.filter(x=>!x.read).length;if(unread){if(count)count.textContent=unread;else{const b=document.getElementById('pro-notification-btn');if(b)b.insertAdjacentHTML('beforeend',`<span class="pro-notification-count">${unread}</span>`)}}else if(count)count.remove()});
})();
