-- SLOGI v72 — база мониторинга объявлений ЦИАН/Авито.
-- Supabase -> SQL Editor -> New query -> вставить целиком -> Run.

begin;

create table if not exists public.slogi_market_listings (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('cian','avito')),
  listing_url text not null,
  address text,
  cluster_name text,
  area numeric,
  floor numeric,
  rent_monthly numeric,
  previous_rent_monthly numeric,
  latitude double precision,
  longitude double precision,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_checked_at timestamptz not null default now(),
  market_status text not null default 'new' check (market_status in ('new','active','removed')),
  price_changed boolean not null default false,
  missed_scans integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source, listing_url)
);

create table if not exists public.slogi_market_price_history (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('cian','avito')),
  listing_url text not null,
  rent_monthly numeric not null,
  recorded_at timestamptz not null default now()
);

create index if not exists slogi_market_listings_status_idx on public.slogi_market_listings(market_status);
create index if not exists slogi_market_listings_source_idx on public.slogi_market_listings(source);
create index if not exists slogi_market_listings_seen_idx on public.slogi_market_listings(last_seen_at desc);
create index if not exists slogi_market_listings_cluster_idx on public.slogi_market_listings(cluster_name);
create index if not exists slogi_market_listings_area_idx on public.slogi_market_listings(area);
create index if not exists slogi_market_price_history_listing_idx on public.slogi_market_price_history(source, listing_url, recorded_at desc);

alter table public.slogi_market_listings enable row level security;
alter table public.slogi_market_price_history enable row level security;

-- Браузер напрямую эти таблицы не меняет: запись идёт только через Edge Function с service_role.
revoke all on public.slogi_market_listings from anon, authenticated;
revoke all on public.slogi_market_price_history from anon, authenticated;
grant all on public.slogi_market_listings to service_role;
grant all on public.slogi_market_price_history to service_role;

commit;
