-- v76.1 forward-only listing refresh schema.
-- The frozen 20260814_7601_baseline.sql migration remains unchanged.

alter table public.slogi_market_listings
  add column external_id text null,
  add column title text null,
  add column description text null,
  add column total_floors numeric null,
  add column ceiling_height numeric null,
  add column published_at timestamptz null,
  add column source_updated_at timestamptz null,
  add column freshness_at timestamptz null,
  add column freshness_kind text null,
  add column date_confidence text null,
  add column parse_completeness numeric null,
  add column parse_warnings jsonb not null default '[]'::jsonb,
  add constraint slogi_market_listings_freshness_kind_check
    check (freshness_kind is null or freshness_kind = any (array['published'::text, 'updated'::text])),
  add constraint slogi_market_listings_parse_completeness_check
    check (parse_completeness is null or (parse_completeness >= 0 and parse_completeness <= 1));

create index slogi_market_listings_freshness_idx
  on public.slogi_market_listings using btree (freshness_at desc);

create index slogi_market_listings_source_freshness_idx
  on public.slogi_market_listings using btree (source, freshness_at desc);

create table public.slogi_listing_scan_state (
  source text not null,
  next_page integer not null default 2,
  discovery_failures integer not null default 0,
  hydration_failures integer not null default 0,
  last_discovery_started_at timestamptz null,
  last_discovery_succeeded_at timestamptz null,
  last_discovery_error_code text null,
  last_hydration_started_at timestamptz null,
  last_hydration_succeeded_at timestamptz null,
  last_hydration_error_code text null,
  cooldown_until timestamptz null,
  updated_at timestamptz not null default now(),

  constraint slogi_listing_scan_state_pkey primary key (source),
  constraint slogi_listing_scan_state_source_check
    check (source = 'cian'),
  constraint slogi_listing_scan_state_next_page_check check (next_page >= 2),
  constraint slogi_listing_scan_state_failure_counts_check
    check (discovery_failures >= 0 and hydration_failures >= 0)
);

create table public.slogi_listing_scan_runs (
  id bigint generated by default as identity not null,
  run_slot timestamptz not null,
  source text not null,
  phase text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz null,
  status text not null default 'running',
  discovered integer not null default 0,
  queued_new integer not null default 0,
  queued_existing integer not null default 0,
  hot integer not null default 0,
  backfill integer not null default 0,
  claimed integer not null default 0,
  attempted integer not null default 0,
  parsed integer not null default 0,
  partial integer not null default 0,
  blocked integer not null default 0,
  failed integer not null default 0,
  inserted integer not null default 0,
  updated integer not null default 0,
  skipped_old integer not null default 0,
  skipped_unknown_date integer not null default 0,
  strategy text null,
  error_code text null,
  diagnostic jsonb not null default '{}'::jsonb,

  constraint slogi_listing_scan_runs_pkey primary key (id),
  constraint slogi_listing_scan_runs_source_check
    check (source = 'cian'),
  constraint slogi_listing_scan_runs_phase_check
    check (phase = any (array['discovery'::text, 'hydration'::text])),
  constraint slogi_listing_scan_runs_status_check
    check (status = any (array['running'::text, 'ok'::text, 'partial'::text, 'blocked'::text, 'failed'::text, 'cooldown'::text, 'timed_out'::text, 'empty'::text])),
  constraint slogi_listing_scan_runs_counts_check
    check (
      discovered >= 0 and queued_new >= 0 and queued_existing >= 0 and hot >= 0 and
      backfill >= 0 and claimed >= 0 and attempted >= 0 and parsed >= 0 and partial >= 0 and
      blocked >= 0 and failed >= 0 and inserted >= 0 and updated >= 0 and
      skipped_old >= 0 and skipped_unknown_date >= 0
    ),
  constraint slogi_listing_scan_runs_source_phase_slot_key unique (source, phase, run_slot)
);

create index slogi_listing_scan_runs_started_idx
  on public.slogi_listing_scan_runs using btree (started_at desc);

create table public.slogi_listing_fetch_queue (
  id bigint generated by default as identity not null,
  source text not null,
  listing_url text not null,
  external_id text null,
  priority text not null,
  status text not null,
  discovered_at timestamptz not null,
  last_discovered_at timestamptz not null,
  next_attempt_at timestamptz not null,
  attempt_count integer not null default 0,
  locked_at timestamptz null,
  locked_by uuid null,
  last_attempt_at timestamptz null,
  completed_at timestamptz null,
  last_error_code text null,
  diagnostic jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint slogi_listing_fetch_queue_pkey primary key (id),
  constraint slogi_listing_fetch_queue_source_url_key unique (source, listing_url),
  constraint slogi_listing_fetch_queue_source_check
    check (source = 'cian'),
  constraint slogi_listing_fetch_queue_priority_check
    check (priority = any (array['hot'::text, 'backfill'::text])),
  constraint slogi_listing_fetch_queue_status_check
    check (status = any (array[
      'pending'::text, 'processing'::text, 'retry'::text, 'completed'::text,
      'discarded_old'::text, 'discarded_unknown_date'::text,
      'blocked'::text, 'failed'::text
    ])),
  constraint slogi_listing_fetch_queue_attempt_count_check check (attempt_count >= 0)
);

create index slogi_listing_fetch_queue_ready_idx
  on public.slogi_listing_fetch_queue using btree (source, status, next_attempt_at, priority);

create index slogi_listing_fetch_queue_stale_processing_idx
  on public.slogi_listing_fetch_queue using btree (locked_at)
  where status = 'processing';

create index slogi_listing_fetch_queue_last_discovery_idx
  on public.slogi_listing_fetch_queue using btree (source, last_discovered_at desc);

alter table public.slogi_listing_scan_state owner to postgres;
alter table public.slogi_listing_scan_runs owner to postgres;
alter table public.slogi_listing_fetch_queue owner to postgres;
alter sequence public.slogi_listing_scan_runs_id_seq owner to postgres;
alter sequence public.slogi_listing_fetch_queue_id_seq owner to postgres;

alter table public.slogi_listing_scan_state enable row level security;
alter table public.slogi_listing_scan_runs enable row level security;
alter table public.slogi_listing_fetch_queue enable row level security;
alter table public.slogi_listing_scan_state no force row level security;
alter table public.slogi_listing_scan_runs no force row level security;
alter table public.slogi_listing_fetch_queue no force row level security;

revoke all on public.slogi_listing_scan_state from public, anon, authenticated, service_role;
revoke all on public.slogi_listing_scan_runs from public, anon, authenticated, service_role;
revoke all on public.slogi_listing_fetch_queue from public, anon, authenticated, service_role;
revoke all on sequence public.slogi_listing_scan_runs_id_seq from public, anon, authenticated, service_role;
revoke all on sequence public.slogi_listing_fetch_queue_id_seq from public, anon, authenticated, service_role;

grant select, insert, update
  on public.slogi_listing_scan_state to service_role;
grant select, insert, update
  on public.slogi_listing_scan_runs to service_role;
grant select, insert, update
  on public.slogi_listing_fetch_queue to service_role;
grant usage, select
  on sequence public.slogi_listing_scan_runs_id_seq to service_role;
grant usage, select
  on sequence public.slogi_listing_fetch_queue_id_seq to service_role;

-- Atomically claim a new daily source slot or reclaim one that has remained
-- running past the caller-provided conservative stale threshold. Updating
-- started_at inside the same statement prevents two retries from reclaiming
-- the same stale row.
create or replace function public.slogi_claim_listing_scan_run(
  p_source text,
  p_phase text,
  p_run_slot timestamptz,
  p_started_at timestamptz,
  p_stale_before timestamptz
)
returns table (run_id bigint, claimed boolean, recovered boolean)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_run_id bigint;
begin
  if p_source is distinct from 'cian' then
    raise exception using errcode = '22023', message = 'invalid_listing_source';
  end if;
  if p_phase is null or p_phase <> all (array['discovery'::text, 'hydration'::text]) then
    raise exception using errcode = '22023', message = 'invalid_listing_phase';
  end if;

  insert into public.slogi_listing_scan_runs (source, phase, run_slot, started_at, status)
  values (p_source, p_phase, p_run_slot, p_started_at, 'running')
  on conflict (source, phase, run_slot) do nothing
  returning id into v_run_id;

  if v_run_id is not null then
    return query select v_run_id, true, false;
    return;
  end if;

  update public.slogi_listing_scan_runs
  set
    started_at = p_started_at,
    finished_at = null,
    status = 'running',
    discovered = 0,
    queued_new = 0,
    queued_existing = 0,
    hot = 0,
    backfill = 0,
    claimed = 0,
    attempted = 0,
    parsed = 0,
    partial = 0,
    blocked = 0,
    failed = 0,
    inserted = 0,
    updated = 0,
    skipped_old = 0,
    skipped_unknown_date = 0,
    strategy = null,
    error_code = 'stale_run_recovered',
    diagnostic = jsonb_build_object(
      'recovery', 'stale_running_reclaimed',
      'recovered_at', p_started_at
    )
  where source = p_source
    and phase = p_phase
    and run_slot = p_run_slot
    and status = 'running'
    and started_at <= p_stale_before
  returning id into v_run_id;

  if v_run_id is not null then
    return query select v_run_id, true, true;
    return;
  end if;

  return query select null::bigint, false, false;
end;
$$;

alter function public.slogi_claim_listing_scan_run(text, text, timestamptz, timestamptz, timestamptz) owner to postgres;
revoke all on function public.slogi_claim_listing_scan_run(text, text, timestamptz, timestamptz, timestamptz)
  from public, anon, authenticated, service_role;
grant execute on function public.slogi_claim_listing_scan_run(text, text, timestamptz, timestamptz, timestamptz)
  to service_role;

-- Discovery materializes canonical URLs only. It never treats discovered_at
-- as publication freshness and it never unlocks an in-flight item.
create or replace function public.slogi_enqueue_listing_fetches(
  p_source text,
  p_priority text,
  p_items jsonb,
  p_discovered_at timestamptz
)
returns table (listing_url text, queue_status text, queued_new boolean)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_item jsonb;
  v_url text;
  v_external_id text;
  v_status text;
  v_new boolean;
begin
  if p_source is distinct from 'cian' then
    raise exception using errcode = '22023', message = 'invalid_listing_source';
  end if;
  if p_priority is null or p_priority <> all (array['hot'::text, 'backfill'::text]) then
    raise exception using errcode = '22023', message = 'invalid_listing_priority';
  end if;
  if p_discovered_at is null or pg_catalog.jsonb_typeof(p_items) <> 'array' or pg_catalog.jsonb_array_length(p_items) > 500 then
    raise exception using errcode = '22023', message = 'invalid_listing_queue_batch';
  end if;

  for v_item in select value from pg_catalog.jsonb_array_elements(p_items)
  loop
    v_url := pg_catalog.btrim(v_item ->> 'listingUrl');
    v_external_id := nullif(pg_catalog.btrim(v_item ->> 'externalId'), '');
    if v_url is null or v_url = '' or pg_catalog.length(v_url) > 2048 then
      raise exception using errcode = '22023', message = 'invalid_listing_url';
    end if;

    insert into public.slogi_listing_fetch_queue as q (
      source, listing_url, external_id, priority, status,
      discovered_at, last_discovered_at, next_attempt_at,
      created_at, updated_at
    ) values (
      p_source, v_url, v_external_id, p_priority, 'pending',
      p_discovered_at, p_discovered_at, p_discovered_at,
      p_discovered_at, p_discovered_at
    )
    on conflict on constraint slogi_listing_fetch_queue_source_url_key do update
    set
      external_id = coalesce(excluded.external_id, q.external_id),
      priority = case when excluded.priority = 'hot' then 'hot' else q.priority end,
      last_discovered_at = excluded.last_discovered_at,
      status = case
        when q.status = 'processing' then q.status
        when q.status in ('failed', 'blocked') and q.next_attempt_at > excluded.last_discovered_at then q.status
        when excluded.priority = 'hot'
          and coalesce(q.last_attempt_at, q.completed_at, q.discovered_at) <= excluded.last_discovered_at - interval '1 hour'
          then 'pending'
        when excluded.priority = 'backfill'
          and coalesce(q.last_attempt_at, q.completed_at, q.discovered_at) <= excluded.last_discovered_at - interval '24 hours'
          then 'pending'
        else q.status
      end,
      next_attempt_at = case
        when q.status = 'processing' then q.next_attempt_at
        when q.status in ('failed', 'blocked') and q.next_attempt_at > excluded.last_discovered_at then q.next_attempt_at
        when excluded.priority = 'hot'
          and coalesce(q.last_attempt_at, q.completed_at, q.discovered_at) <= excluded.last_discovered_at - interval '1 hour'
          then excluded.last_discovered_at
        when excluded.priority = 'backfill'
          and coalesce(q.last_attempt_at, q.completed_at, q.discovered_at) <= excluded.last_discovered_at - interval '24 hours'
          then excluded.last_discovered_at
        else q.next_attempt_at
      end,
      locked_at = case when q.status = 'processing' then q.locked_at else null end,
      locked_by = case when q.status = 'processing' then q.locked_by else null end,
      completed_at = case
        when q.status = 'processing' then q.completed_at
        when (excluded.priority = 'hot' and coalesce(q.last_attempt_at, q.completed_at, q.discovered_at) <= excluded.last_discovered_at - interval '1 hour')
          or (excluded.priority = 'backfill' and coalesce(q.last_attempt_at, q.completed_at, q.discovered_at) <= excluded.last_discovered_at - interval '24 hours')
          then null
        else q.completed_at
      end,
      updated_at = excluded.updated_at
    returning q.status, (xmax = 0) into v_status, v_new;

    return query select v_url, v_status, v_new;
  end loop;
end;
$$;

alter function public.slogi_enqueue_listing_fetches(text, text, jsonb, timestamptz) owner to postgres;
revoke all on function public.slogi_enqueue_listing_fetches(text, text, jsonb, timestamptz)
  from public, anon, authenticated, service_role;
grant execute on function public.slogi_enqueue_listing_fetches(text, text, jsonb, timestamptz)
  to service_role;

-- Claim at most two due rows with SKIP LOCKED. Stale processing rows become
-- retryable first, which implements a durable visibility timeout.
create or replace function public.slogi_claim_listing_fetch_queue(
  p_source text,
  p_worker_id uuid,
  p_batch_limit integer,
  p_claimed_at timestamptz,
  p_stale_before timestamptz
)
returns setof public.slogi_listing_fetch_queue
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_limit integer;
begin
  if p_source is distinct from 'cian' then
    raise exception using errcode = '22023', message = 'invalid_listing_source';
  end if;
  if p_worker_id is null or p_claimed_at is null or p_stale_before is null then
    raise exception using errcode = '22023', message = 'invalid_listing_claim';
  end if;
  v_limit := greatest(1, least(2, coalesce(p_batch_limit, 1)));

  update public.slogi_listing_fetch_queue
  set
    status = 'retry', locked_at = null, locked_by = null,
    next_attempt_at = p_claimed_at, last_error_code = 'stale_processing_recovered',
    updated_at = p_claimed_at
  where source = p_source and status = 'processing' and locked_at <= p_stale_before;

  return query
  with candidates as (
    select q.id
    from public.slogi_listing_fetch_queue as q
    where q.source = p_source
      and q.status = any (array['pending'::text, 'retry'::text])
      and q.next_attempt_at <= p_claimed_at
    order by case q.priority when 'hot' then 0 else 1 end, q.next_attempt_at, q.id
    for update skip locked
    limit v_limit
  )
  update public.slogi_listing_fetch_queue as q
  set
    status = 'processing', locked_at = p_claimed_at, locked_by = p_worker_id,
    last_attempt_at = p_claimed_at, attempt_count = q.attempt_count + 1,
    updated_at = p_claimed_at
  from candidates
  where q.id = candidates.id
  returning q.*;
end;
$$;

alter function public.slogi_claim_listing_fetch_queue(text, uuid, integer, timestamptz, timestamptz) owner to postgres;
revoke all on function public.slogi_claim_listing_fetch_queue(text, uuid, integer, timestamptz, timestamptz)
  from public, anon, authenticated, service_role;
grant execute on function public.slogi_claim_listing_fetch_queue(text, uuid, integer, timestamptz, timestamptz)
  to service_role;

create or replace function public.slogi_finish_listing_fetch_queue(
  p_id bigint,
  p_worker_id uuid,
  p_status text,
  p_finished_at timestamptz,
  p_next_attempt_at timestamptz,
  p_error_code text,
  p_diagnostic jsonb
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_updated bigint;
begin
  if p_status is null or p_status <> all (array[
    'retry'::text, 'completed'::text, 'discarded_old'::text,
    'discarded_unknown_date'::text, 'blocked'::text, 'failed'::text
  ]) then
    raise exception using errcode = '22023', message = 'invalid_listing_queue_status';
  end if;
  if p_worker_id is null or p_finished_at is null then
    raise exception using errcode = '22023', message = 'invalid_listing_finish';
  end if;
  if p_status = 'retry' and (p_next_attempt_at is null or p_next_attempt_at <= p_finished_at) then
    raise exception using errcode = '22023', message = 'invalid_listing_retry_time';
  end if;

  update public.slogi_listing_fetch_queue
  set
    status = p_status,
    next_attempt_at = coalesce(p_next_attempt_at, p_finished_at),
    locked_at = null,
    locked_by = null,
    completed_at = case when p_status = 'completed' then p_finished_at else completed_at end,
    last_error_code = nullif(pg_catalog.btrim(p_error_code), ''),
    diagnostic = coalesce(p_diagnostic, '{}'::jsonb),
    updated_at = p_finished_at
  where id = p_id and status = 'processing' and locked_by = p_worker_id;

  get diagnostics v_updated = row_count;
  return v_updated = 1;
end;
$$;

alter function public.slogi_finish_listing_fetch_queue(bigint, uuid, text, timestamptz, timestamptz, text, jsonb) owner to postgres;
revoke all on function public.slogi_finish_listing_fetch_queue(bigint, uuid, text, timestamptz, timestamptz, text, jsonb)
  from public, anon, authenticated, service_role;
grant execute on function public.slogi_finish_listing_fetch_queue(bigint, uuid, text, timestamptz, timestamptz, text, jsonb)
  to service_role;

insert into public.slogi_listing_scan_state (source)
values ('cian')
on conflict (source) do nothing;
