/*
============================================================
SLOGI v76.0.1 — TECHNICAL BASELINE FREEZE
Database baseline snapshot

Baseline identity date: 2026-08-14
Snapshot materialized: 2026-08-15
Production authority: Supabase project badyvlegwumldciibxfe

PURPOSE
-------
Reproduce the factual SLOGI v76 public database baseline in a CLEAN
Supabase environment.

IMPORTANT
---------
1. DO NOT APPLY BLINDLY TO EXISTING PRODUCTION.
2. This file contains schema/RLS/policy facts reconstructed from the
   live production metadata exports supplied during the v76.0.1 freeze.
3. The identity property of the two market-table "id" columns is taken
   from the recovered SUPABASE_MARKET_ANALYSIS_V72.sql. The v76 release
   documentation states that the v72 market SQL schema was unchanged.
4. Storage bucket configuration and storage.objects policy definitions
   are taken from the recovered SUPABASE_SETUP.sql and are consistent
   with the observed live bucket (slogi-files, 50 MiB, 4 policies), but
   the exact live storage policy expressions were not independently
   fingerprinted during this freeze.
5. Data API grants are reproduced from the recovered setup SQL because
   live table privilege grants were not separately fingerprinted.

This baseline intentionally DOES NOT redesign the schema.
============================================================
*/

begin;

-- ==========================================================
-- 1. CORE CLOUD STATE TABLES
-- ==========================================================

create table public.slogi_user_state (
  user_id uuid not null,
  locations jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint slogi_user_state_pkey primary key (user_id),
  constraint slogi_user_state_user_id_fkey
    foreign key (user_id) references auth.users(id) on delete cascade
);

create table public.slogi_workspace_state (
  user_id uuid not null,
  workspace jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint slogi_workspace_state_pkey primary key (user_id),
  constraint slogi_workspace_state_user_id_fkey
    foreign key (user_id) references auth.users(id) on delete cascade
);

create table public.slogi_attachments (
  user_id uuid not null,
  location_id text not null,
  attachment_type text not null,
  file_name text not null default 'Файл'::text,
  mime_type text not null default 'application/octet-stream'::text,
  storage_path text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint slogi_attachments_pkey
    primary key (user_id, location_id, attachment_type),
  constraint slogi_attachments_user_id_fkey
    foreign key (user_id) references auth.users(id) on delete cascade
);

-- ==========================================================
-- 2. MARKET ANALYSIS TABLES
-- ==========================================================

create table public.slogi_market_listings (
  id bigint generated by default as identity not null,
  source text not null,
  listing_url text not null,
  address text,
  cluster_name text,
  area numeric,
  floor numeric,
  rent_monthly numeric,
  previous_rent_monthly numeric,
  latitude double precision,
  longitude double precision,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_checked_at timestamptz not null default now(),
  market_status text not null default 'new'::text,
  price_changed boolean not null default false,
  missed_scans integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint slogi_market_listings_pkey
    primary key (id),

  constraint slogi_market_listings_source_check
    check (source = any (array['cian'::text, 'avito'::text])),

  constraint slogi_market_listings_market_status_check
    check (market_status = any (
      array['new'::text, 'active'::text, 'removed'::text]
    )),

  constraint slogi_market_listings_source_listing_url_key
    unique (source, listing_url)
);

create table public.slogi_market_price_history (
  id bigint generated by default as identity not null,
  source text not null,
  listing_url text not null,
  rent_monthly numeric not null,
  recorded_at timestamptz not null default now(),

  constraint slogi_market_price_history_pkey
    primary key (id),

  constraint slogi_market_price_history_source_check
    check (source = any (array['cian'::text, 'avito'::text]))
);

-- ==========================================================
-- 3. NON-CONSTRAINT INDEXES
-- ==========================================================
-- PostgreSQL automatically creates indexes for PRIMARY KEY and UNIQUE
-- constraints. Only additional live indexes are declared here.

create index slogi_market_listings_area_idx
  on public.slogi_market_listings using btree (area);

create index slogi_market_listings_cluster_idx
  on public.slogi_market_listings using btree (cluster_name);

create index slogi_market_listings_seen_idx
  on public.slogi_market_listings using btree (last_seen_at desc);

create index slogi_market_listings_source_idx
  on public.slogi_market_listings using btree (source);

create index slogi_market_listings_status_idx
  on public.slogi_market_listings using btree (market_status);

create index slogi_market_price_history_listing_idx
  on public.slogi_market_price_history
  using btree (source, listing_url, recorded_at desc);

-- ==========================================================
-- 4. ROW LEVEL SECURITY — LIVE FACTUAL STATE
-- ==========================================================
-- Live metadata:
--   relrowsecurity = true  on all five public tables
--   relforcerowsecurity = false on all five public tables

alter table public.slogi_attachments enable row level security;
alter table public.slogi_market_listings enable row level security;
alter table public.slogi_market_price_history enable row level security;
alter table public.slogi_user_state enable row level security;
alter table public.slogi_workspace_state enable row level security;

-- Do NOT FORCE RLS: production relforcerowsecurity = false.

-- ==========================================================
-- 5. LIVE PUBLIC-SCHEMA RLS POLICIES
-- ==========================================================
-- Live pg_policies contains 12 policies, all on the three user-owned
-- tables below. There are NO pg_policies for either market table.

create policy "SLOGI attachments select own"
on public.slogi_attachments
as permissive
for select
to authenticated
using ((select auth.uid() as uid) = user_id);

create policy "SLOGI attachments insert own"
on public.slogi_attachments
as permissive
for insert
to authenticated
with check ((select auth.uid() as uid) = user_id);

create policy "SLOGI attachments update own"
on public.slogi_attachments
as permissive
for update
to authenticated
using ((select auth.uid() as uid) = user_id)
with check ((select auth.uid() as uid) = user_id);

create policy "SLOGI attachments delete own"
on public.slogi_attachments
as permissive
for delete
to authenticated
using ((select auth.uid() as uid) = user_id);


create policy "SLOGI state select own"
on public.slogi_user_state
as permissive
for select
to authenticated
using ((select auth.uid() as uid) = user_id);

create policy "SLOGI state insert own"
on public.slogi_user_state
as permissive
for insert
to authenticated
with check ((select auth.uid() as uid) = user_id);

create policy "SLOGI state update own"
on public.slogi_user_state
as permissive
for update
to authenticated
using ((select auth.uid() as uid) = user_id)
with check ((select auth.uid() as uid) = user_id);

create policy "SLOGI state delete own"
on public.slogi_user_state
as permissive
for delete
to authenticated
using ((select auth.uid() as uid) = user_id);


create policy "SLOGI workspace select own"
on public.slogi_workspace_state
as permissive
for select
to authenticated
using ((select auth.uid() as uid) = user_id);

create policy "SLOGI workspace insert own"
on public.slogi_workspace_state
as permissive
for insert
to authenticated
with check ((select auth.uid() as uid) = user_id);

create policy "SLOGI workspace update own"
on public.slogi_workspace_state
as permissive
for update
to authenticated
using ((select auth.uid() as uid) = user_id)
with check ((select auth.uid() as uid) = user_id);

create policy "SLOGI workspace delete own"
on public.slogi_workspace_state
as permissive
for delete
to authenticated
using ((select auth.uid() as uid) = user_id);

-- ==========================================================
-- 6. RECOVERED DATA API GRANT CONTRACT
-- ==========================================================
-- Reproduced from recovered setup SQL.
-- Table grants were not independently live-fingerprinted during freeze.

revoke all on public.slogi_user_state from anon;
revoke all on public.slogi_workspace_state from anon;
revoke all on public.slogi_attachments from anon;

grant select, insert, update, delete
  on public.slogi_user_state to authenticated;
grant select, insert, update, delete
  on public.slogi_workspace_state to authenticated;
grant select, insert, update, delete
  on public.slogi_attachments to authenticated;

grant all on public.slogi_user_state to service_role;
grant all on public.slogi_workspace_state to service_role;
grant all on public.slogi_attachments to service_role;

-- Market tables are server-side only in the recovered v72/v76 contract.
revoke all on public.slogi_market_listings from anon, authenticated;
revoke all on public.slogi_market_price_history from anon, authenticated;
grant all on public.slogi_market_listings to service_role;
grant all on public.slogi_market_price_history to service_role;

-- Identity sequence privileges are needed for service-role inserts in
-- a clean environment.
grant usage, select
  on sequence public.slogi_market_listings_id_seq
  to service_role;

grant usage, select
  on sequence public.slogi_market_price_history_id_seq
  to service_role;

-- ==========================================================
-- 7. STORAGE BASELINE
-- ==========================================================
-- Live observations:
--   bucket = slogi-files
--   file size limit = 50 MiB
--   allowed MIME types = Any
--   policies observed = 4
--
-- The policy definitions below are reproduced from recovered
-- SUPABASE_SETUP.sql and are consistent with that observed topology.

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'slogi-files',
  'slogi-files',
  false,
  52428800,
  null
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "SLOGI files select own" on storage.objects;
drop policy if exists "SLOGI files insert own" on storage.objects;
drop policy if exists "SLOGI files update own" on storage.objects;
drop policy if exists "SLOGI files delete own" on storage.objects;

create policy "SLOGI files select own"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'slogi-files'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy "SLOGI files insert own"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'slogi-files'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy "SLOGI files update own"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'slogi-files'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
)
with check (
  bucket_id = 'slogi-files'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy "SLOGI files delete own"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'slogi-files'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

commit;

/*
============================================================
VALIDATION TARGET FOR CLEAN-ENV REPRODUCTION

Expected public tables: 5
Expected public-table RLS: enabled on all 5
Expected FORCE RLS: false on all 5
Expected public pg_policies: 12
Expected non-constraint indexes: 6
Expected named table constraints: 12

Expected market-table client policies:
  slogi_market_listings       -> 0
  slogi_market_price_history  -> 0

Expected Storage bucket:
  slogi-files
  private
  50 MiB
  any MIME type
  4 storage.objects policies

DO NOT mark this release frozen until this file is committed and the
repository working tree is clean.
============================================================
*/
